trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x.x'

- script: dotnet build --configuration Release
  displayName: 'Build Project'

- script: dotnet test
  displayName: 'Run Tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure Subscription Name>'
    appName: '<Your Web App Name>'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
